### PR TITLE
fixes #84

### LINKED ISSUE #84: The directory /private is not writable
Screenshot_20210523_144044

I had a similar issue with the redis container on my setup, I needed to change its stanza to:

```
redis:
  enabled: true
  persistence:
    enabled: true
    storageClass: openebs-lvmpv
    size: 8Gi
  volumePermissions:
    enabled: true
```
full [values.yaml](https://gist.github.com/joshuacox/4f41f14aaa0a3b285ae3e09a5d1f17fb)

Is there a similar `volumePermissions` stanza I can add to the drupal container?  I did try just adding that exact stanza to the drupal with no luck.

I am using the [lvm-localpv](https://github.com/openebs/lvm-localpv) driver for openEBS.  But all looks to be okay there:

```
➜  drupal git:(master) ✗ kubectl get sc openebs-lvmpv
NAME                      PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
openebs-lvmpv (default)   local.csi.openebs.io   Delete          Immediate           false                  78m
➜  drupal git:(master) ✗ kubectl get pvc              
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
drupal-drupal                      Bound    pvc-d1d2b924-5138-4225-8fc6-1ca42d2ef3f2   8Gi        RWO            openebs-lvmpv   12m
drupal-mysql                       Bound    pvc-ec368551-cc28-48eb-b22e-edf41c971fcc   8Gi        RWO            openebs-lvmpv   12m
drupal-nginx                       Bound    pvc-c90ca6d5-427d-487a-9c6b-fa88fdd05de6   8Gi        RWO            openebs-lvmpv   12m
redis-data-drupal-redis-master-0   Bound    pvc-73180e38-cb7b-4a60-bbc6-1e32e78fbae3   8Gi        RWO            openebs-lvmpv   12m
redis-data-drupal-redis-slave-0    Bound    pvc-109dea85-656d-4d41-baff-0e94d45c55d9   8Gi        RWO            openebs-lvmpv   12m
redis-data-drupal-redis-slave-1    Bound    pvc-6dd2c58b-8373-4bab-9aee-e5033c58b745   8Gi        RWO            openebs-lvmpv   11m
➜  drupal git:(master) ✗ kubectl get pv 
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                      STORAGECLASS    REASON   AGE
pvc-109dea85-656d-4d41-baff-0e94d45c55d9   8Gi        RWO            Delete           Bound    default/redis-data-drupal-redis-slave-0    openebs-lvmpv            12m
pvc-6dd2c58b-8373-4bab-9aee-e5033c58b745   8Gi        RWO            Delete           Bound    default/redis-data-drupal-redis-slave-1    openebs-lvmpv            11m
pvc-73180e38-cb7b-4a60-bbc6-1e32e78fbae3   8Gi        RWO            Delete           Bound    default/redis-data-drupal-redis-master-0   openebs-lvmpv            12m
pvc-c90ca6d5-427d-487a-9c6b-fa88fdd05de6   8Gi        RWO            Delete           Bound    default/drupal-nginx                       openebs-lvmpv            12m
pvc-d1d2b924-5138-4225-8fc6-1ca42d2ef3f2   8Gi        RWO            Delete           Bound    default/drupal-drupal                      openebs-lvmpv            12m
pvc-ec368551-cc28-48eb-b22e-edf41c971fcc   8Gi        RWO            Delete           Bound    default/drupal-mysql                       openebs-lvmpv            12m
➜  drupal git:(master) ✗ kubectl get po
NAME                                      READY   STATUS    RESTARTS   AGE
drupal-765f49855f-lf5vc                   3/3     Running   0          17m
drupal-mysql-7b7769b55d-n24sd             2/2     Running   0          17m
drupal-nginx-6f57fc6dd6-zw794             2/2     Running   0          17m
drupal-redis-master-0                     2/2     Running   0          17m
drupal-redis-slave-0                      2/2     Running   0          17m
drupal-redis-slave-1                      2/2     Running   0          16m
drupal-varnish-787c7f8cfc-6bs77           2/2     Running   0          17m
```
It seems to me that whatever the redis pod is doing with:

```
  volumePermissions:
    enabled: true
```

The drupal pod needs to do the same thing?  I assume a chown or chmod, or perhaps a change of user.

### PR DESCRIPTION
**Pull request by joshuacox**
This adds an example initContainer that should fix permission issues.

Signed-off-by: Josh Cox <josh@webhosting.coop>

### CODE REVIEW

**Comment by joshuacox** [comment]
Closes #84

**Comment by sylus** [comment]
This looks good to me :D 

Is it possible to uncomment the values.yaml and set it to be false? The only minor nit I see, else I can merge this.

@zachomedia look good to you so others don't hit this problem?

**Comment by joshuacox** [comment]
I tested it by running as `false` and, indeed, the initcontainer is not created, and the setup fails again at

```
 [error]  The file permissions could not be set on sites/default/files. 
 [error]  The file permissions could not be set on /private. 
```

So I think that leaving it uncommented and set on `false` is just fine.

**Review by zachomedia — CHANGES_REQUESTED** [review]
This looks great @joshuacox! Can you do one last thing and increase the `version` field in 	`Chart.yaml`? Thanks!

**Comment by joshuacox** [comment]
Sorry I missed this one, I had just left to Travel to Colorado.  Looks like it got merged in anyhow.  @zachomedia let me know if I can anything else.  I'll look forward to making contributions in the future.

**Pull request merged**
