### PR TITLE
Redis chart version update

### PR DESCRIPTION
**Pull request by bernardmaltais**
The current version of redis is VERY VERY VERY old and does not offer support for nodeSelector and other goodies. Updating to the latest version allow for better positioning of redis pods and improve site performance.

@sylus  I am leaving the chart version update to you guys since this is my 3rd pull request and I have no idea which will be accepted and which will not.

### CODE REVIEW

**Comment by sylus** [comment]
Yeah ive been meaning to get around to this, with this jump did any of the sub params change or they all still the same?

**Comment by bernardmaltais** [comment]
I noticed only that the default replicaCount is now 3 and since it was not set in the example you provided I had to add the following to bring it back to two:

```yaml
  replica:
   replicaCount: 2
```

**Comment by bernardmaltais** [comment]
This is my current config for redis which appear to be fast at all time using the latest chart release:

```yaml
redis:
  enabled: true
  password: ${var.redis_password_rsams}
  # image:
  #   registry: docker.io
  #   repository: bitnami/redis
  #   tag: 6.0.12-debian-10-r33
  #   clientInterface: PhpRedis
  # cluster:
  #   enabled: true
  #   slaveCount: 2
  sentinel:
    enabled: false
  master:
    service:
      type: ClusterIP
    disableCommands: []
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - sand
    nodeSelector:
      env: sand
  slave:
    service:
      type: ClusterIP
    disableCommands: []
    nodeSelector:
      env: sand
  replica:
   replicaCount: 2
```

Let me know if I should tune a few things ;-)

**Comment by zachomedia** [comment]
This also looks good! I just want to confirm a couple of things in my local test and then it'll be good to merge :) Thank you!

**Comment by zachomedia** [comment]
Ok, I have tested this and it looks good. Only thing was the redis master statefulset needed to be manually removed: `Error: UPGRADE FAILED: cannot patch "wxt-redis-master" with kind StatefulSet: StatefulSet.apps "wxt-redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden`.

I'll make a note of this in the changelog and make the appropriate version number bump to indicate this. Thanks!

**Review by zachomedia — APPROVED** [review]

**Pull request merged**
