### PR TITLE
Adding tolerations and nodeSelector support to chart

### PR DESCRIPTION
**Pull request by bernardmaltais**
Add support for tolerations and nodeSelector placement to Drupal9 Deployments and CronJobs

### CODE REVIEW

**Comment by bernardmaltais** [comment]
@zachomedia @sylus The mysql chart support both tolerations and nodeSelector but the statcan varnish chart does not... It would be nice if toleration and nodeSelector support was added to it also.

**Comment by bernardmaltais** [comment]
I actually created a pull request to add the missing plumbing to the varnish chart for toleration and nodeSelector support: https://github.com/StatCan/charts/pull/48

**Comment by sylus** [comment]
This looks good to me but might want @zachomedia just to give it a quick glance too :D 

Thanks so much for doing this!

**Comment by bernardmaltais** [comment]
@sylus Indeed. Pleas hold on before merging as I need to update the varnish chart to 0.2.1 since you merged it in the statcan charts repo and I will want to use that also.

**Comment by bernardmaltais** [comment]
OK, I think it is ready for a good review by @zachomedia 
I tested deploying using it to a node pool comprised of spot instance azure VM and all went well. Site is up and responsive.

**Review by zachomedia — CHANGES_REQUESTED** [review]
@bernardmaltais Thank you very much for this! This looks great. The only additional thing that I would like to see on this PR is an example on how to use it in the values.yaml file (commented out), similar to the `drupal.initContainers` (https://github.com/drupalwxt/helm-drupal/blob/master/drupal/values.yaml#L238)

**Comment by bernardmaltais** [comment]
I have added the examples for all the components I have been able to test against... I am pretty sure redis, postgresql already support them...

**Comment by bernardmaltais** [comment]
@zachomedia OK... finally got through all the linting issues. Change request completed ;-)

**Comment by sylus** [comment]
Thanks so much this looks good!

**Pull request merged**
