### PR TITLE
feat(db): Switch MySQL to Bitnami and Upgrade PostgreSQL

### PR DESCRIPTION
**Pull request by sylus**
Even though we state to use Managed Databases in Production for those that do use the containerized versions we need to switch the MySQL containerized to the Bitnami charts due to stable charts deprecation. In addition I updated the PostgreSQL Bitnami chart as both the MySQL and PostgreSQL charts align roughly in configuration values in recent releases

> **Note:** In the changelog I mention this is a breaking change with respect to the MySQL switch and that you must export and restore the database.

@zachomedia could I have your review on this? ^_^

### CODE REVIEW

**Comment by bernardmaltais** [comment]
So, besides the need to restore the DB from a previous backup when switching to this new container for MySQL, there should be no other noticeable issues?

**Comment by sylus** [comment]
@bernardmaltais there shouldn't be no but I should probably make a note to update the syntax for the MySQL | PostgreSQL settings such as setting the password.

**Comment by bernardmaltais** [comment]
@sylus Indeed, there will be a bit of moving values around to the new ones.

**Comment by bernardmaltais** [comment]
@sylus I also noted another difference. The mysql PVC does not get destroyed as part of the uninstallation of the chart. This will leave the mysql PVC permanently mounted and will cause issue if you try to re-deploy the chart without 1st deleting the PVC manually...

**Review by zachomedia — APPROVED** [review]
Change seems reasonable, and documentation is provided to note the breaking change with the containerized database.

**Pull request merged**
