### PR TITLE
Update ingress configs with ingressClassName

### PR DESCRIPTION
**Pull request by markwooff**
The latest Kubernetes versions are removing the deprecated `kubernetes.io/ingress.class` annotation for selecting an Nginx ingress controller and are pushing to use the `.spec.ingressClassName` field (see: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#what-to-do). Adding this into the Ingress configs will allow a developer to set their Ingress class using the format below:

```
ingress:
  enabled: true
  className: my-nginx-class
```

### CODE REVIEW

**Review by zachomedia — COMMENTED** [review]
This looks good @markwooff! Thank you! Can you add a commented-out example of the value in `values.yaml`?

**Comment by markwooff** [comment]
> This looks good @markwooff! Thank you! Can you add a commented-out example of the value in `values.yaml`?

No problem! Just added one in and removed the deprecated `kubernetes.io/ingress.class` annotation.

**Comment by sylus** [comment]
Oh just one more thing can you bump the chart.yaml version as well?

**Comment by markwooff** [comment]
Chart versions have been bumped.

**Review by zachomedia — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
