### PR TITLE
Upgraded Ingress apiVersion to networking.k8s.io/v1

### PR DESCRIPTION
**Pull request by markwooff**
Kubernetes Ingress is now out of beta with the updated `networking.k8s.io/v1` apiVersion requiring some changes to the Ingress YAML. Tested this updated Ingress with our `v1.19.3` AKS cluster and works well.

### CODE REVIEW

**Comment by sylus** [comment]
@zachomedia

**Comment by zachomedia** [comment]
This change is good, but I think we will have to maintain support for the older `v1beta1` as `v1` is only new in 1.19. This should be possibly by checking the Kubernetes version in an `if` condition and apply the appropriate object (https://helm.sh/docs/chart_template_guide/builtin_objects/).

**Comment by sylus** [comment]
@zachomedia so similar to what we doing here?

https://github.com/drupalwxt/helm-drupal/blob/master/drupal/templates/storageclass/shared-disk.yaml

**Comment by sylus** [comment]
```sh
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
provisioner: kubernetes.io/azure-disk
{{- else }}
```

**Comment by zachomedia** [comment]
Yeah, very similar to that!

**Comment by markwooff** [comment]
Thanks for the feedback guys. I've added backwards-compatibility into the Ingress object now, just tested it with our `>= 1.19.0` cluster.

**Review by zachomedia — APPROVED** [review]
Thank you for the contribution and incorporating the backwards compatibility! This LGTM!

**Pull request merged**
