### PR TITLE
Add option to disable gzip compression

### PR DESCRIPTION
**Pull request by markwooff**
Ran into a use case where gzip compression needed to be disabled which currently can't be configured. This change should allow developers to disable it if necessary while having it be on by default.

### CODE REVIEW

**Comment by bernardmaltais** [comment]
Look good to me.

**Comment by markwooff** [comment]
Thanks @bernardmaltais - just made a small update to capture all the gzip configs with the new Helm value.

**Review by zachomedia — CHANGES_REQUESTED** [review]
This looks good, thanks for the contribution @markwooff! Do you mind increasing the version of the chart in Chart.yaml to `0.17.2` for drupal and `0.2.4` fro drupal7? Once that's done, we can merge this!

**Comment by markwooff** [comment]
No problem @zachomedia - just made the requested change so it should be ready to go! Thanks

**Review by zachomedia — APPROVED** [review]

**Comment by zachomedia** [comment]
Thanks!

**Pull request merged**
